name: unid2022
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage:
  http: 0.13.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/background_room.jpg
    - assets/images/ocean.jpg
    - assets/images/letter.jpg
    - assets/images/bo.png
    - assets/images/book_shelf.jpg
    - assets/images/myletterback.png


